<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Member;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            [
                'name' => 'Mohammad Rahman',
                'name_bn' => 'মোহাম্মদ রহমান',
                'father_name' => 'Abdul Haque',
                'mother_name' => 'Fatema Begum',
                'date_of_birth' => '1985-05-15',
                'gender' => 'male',
                'blood_group' => 'A+',
                'mobile' => '+8801700111222',
                'email' => 'rahman@example.com',
                'national_id' => '1234567890123',
                'occupation' => 'Businessman',
                'designation' => 'CEO',
                'company_name' => 'Tech Solutions Ltd',
                'present_address' => 'House 12, Road 5, Dhanmondi, Dhaka 1205',
                'permanent_address' => 'Village: Kamalpur, Thana: Savar, District: Dhaka',
                'emergency_contact_name' => 'Rahim Ahmed',
                'emergency_contact_phone' => '+8801700333444',
                'emergency_contact_relation' => 'Brother',
                'join_date' => '2015-03-20',
                'member_type' => 'founder',
                'status' => true,
                'position' => 'president',
                'nominee_name' => 'Fatema Rahman',
                'nominee_relation' => 'Spouse',
                'nominee_phone' => '+8801700555666',
            ],
            [
                'name' => 'Fatema Begum',
                'name_bn' => 'ফাতেমা বেগম',
                'father_name' => 'Kamal Ahmed',
                'mother_name' => 'Nur Begum',
                'date_of_birth' => '1990-08-22',
                'gender' => 'female',
                'blood_group' => 'O+',
                'mobile' => '+8801700777888',
                'email' => 'fatema@example.com',
                'national_id' => '2345678901234',
                'occupation' => 'Teacher',
                'designation' => 'Senior Teacher',
                'company_name' => 'Dhaka Model School',
                'present_address' => 'House 25, Road 8, Gulshan, Dhaka 1212',
                'permanent_address' => 'Village: Mirpur, Thana: Pallabi, District: Dhaka',
                'emergency_contact_name' => 'Ahmed Khan',
                'emergency_contact_phone' => '+8801700888999',
                'emergency_contact_relation' => 'Husband',
                'join_date' => '2018-06-15',
                'member_type' => 'general',
                'status' => true,
                'position' => 'executive',
                'nominee_name' => 'Ahmed Khan',
                'nominee_relation' => 'Husband',
                'nominee_phone' => '+8801700888999',
            ],
            [
                'name' => 'Abdul Karim',
                'name_bn' => 'আব্দুল করিম',
                'father_name' => 'Rahim Uddin',
                'mother_name' => 'Karima Begum',
                'date_of_birth' => '1988-03-10',
                'gender' => 'male',
                'blood_group' => 'B+',
                'mobile' => '+8801700999000',
                'email' => 'karim@example.com',
                'national_id' => '3456789012345',
                'occupation' => 'Engineer',
                'designation' => 'Project Manager',
                'company_name' => 'Construction Corp',
                'present_address' => 'Flat 5A, House 30, Banani, Dhaka 1213',
                'permanent_address' => 'Village: Tangail Sadar, District: Tangail',
                'emergency_contact_name' => 'Rahima Karim',
                'emergency_contact_phone' => '+8801700111222',
                'emergency_contact_relation' => 'Wife',
                'join_date' => '2019-01-10',
                'member_type' => 'general',
                'status' => true,
                'position' => 'secretary',
                'nominee_name' => 'Rahima Karim',
                'nominee_relation' => 'Wife',
                'nominee_phone' => '+8801700111222',
            ],
            [
                'name' => 'Nusrat Jahan',
                'name_bn' => 'নুসরাত জাহান',
                'father_name' => 'Habibullah',
                'mother_name' => 'Rashida Begum',
                'date_of_birth' => '1992-11-05',
                'gender' => 'female',
                'blood_group' => 'AB+',
                'mobile' => '+8801700221133',
                'email' => 'nusrat@example.com',
                'national_id' => '4567890123456',
                'occupation' => 'Doctor',
                'designation' => 'Medical Officer',
                'company_name' => 'Bangabandhu Sheikh Mujib Medical University',
                'present_address' => 'House 8, Road 12, Uttara, Dhaka 1230',
                'permanent_address' => 'Village: Chittagong Sadar, District: Chittagong',
                'emergency_contact_name' => 'Prof. Ali Ahmed',
                'emergency_contact_phone' => '+8801700334455',
                'emergency_contact_relation' => 'Father',
                'join_date' => '2020-09-01',
                'member_type' => 'general',
                'status' => true,
                'position' => 'member',
                'nominee_name' => 'Ali Ahmed',
                'nominee_relation' => 'Father',
                'nominee_phone' => '+8801700334455',
            ],
            [
                'name' => 'Kamal Hossain',
                'name_bn' => 'কামাল হোসেন',
                'father_name' => 'Ali Miah',
                'mother_name' => 'Rahima Begum',
                'date_of_birth' => '1980-07-20',
                'gender' => 'male',
                'blood_group' => 'A-',
                'mobile' => '+8801700445566',
                'email' => 'kamal@example.com',
                'national_id' => '5678901234567',
                'occupation' => 'Lawyer',
                'designation' => 'Senior Advocate',
                'company_name' => 'Hossain & Associates',
                'present_address' => 'House 15, Road 20, Mirpur, Dhaka 1216',
                'permanent_address' => 'Village: Rajshahi Sadar, District: Rajshahi',
                'emergency_contact_name' => 'Jamila Hossain',
                'emergency_contact_phone' => '+8801700556677',
                'emergency_contact_relation' => 'Wife',
                'join_date' => '2016-04-25',
                'member_type' => 'life',
                'status' => true,
                'position' => 'vice_president',
                'nominee_name' => 'Jamila Hossain',
                'nominee_relation' => 'Wife',
                'nominee_phone' => '+8801700556677',
            ],
        ];

        foreach ($members as $memberData) {
            Member::create($memberData);
        }

        // Create additional random members
        Member::factory()->count(10)->create();

        $this->command->info('Members seeded successfully!');
    }
}
